### ISSUE TITLE
Webpack 2 System.import

### ISSUE THREAD

**Issue by mmahalwy** [morlay/babel-plugin-transform-ensure-ignore#1]
See: https://gist.github.com/sokra/27b24881210b56bbaff7#code-splitting-with-es6

**Comment by morlay** [comment]
For Webpack 2, 
I think this polyfill could be used https://github.com/ModuleLoader/es6-module-loader#nodejs-use, to make System in global.

**Comment by morlay** [comment]
Use this for Webpack2 https://github.com/thgreasi/babel-plugin-system-import-transformer
